#!/usr/bin/python

"""Amulet tests on a basic rabbitmq-server deployment on trusty-icehouse."""

from basic_deployment import RmqBasicDeployment

if __name__ == '__main__':
    deployment = RmqBasicDeployment(series='trusty')
    deployment.run_tests()
