#!/usr/bin/python

"""Amulet tests on a basic rabbitmq-server deployment on trusty-liberty."""

from basic_deployment import RmqBasicDeployment

if __name__ == '__main__':
    deployment = RmqBasicDeployment(series='trusty',
                                    openstack='cloud:trusty-liberty',
                                    source='cloud:trusty-updates/liberty')
    deployment.run_tests()
