#!/usr/bin/python

"""Amulet tests on a basic rabbitmq-server deployment on xenial-mitaka."""

from basic_deployment import RmqBasicDeployment

if __name__ == '__main__':
    deployment = RmqBasicDeployment(series='xenial')
    deployment.run_tests()
