#!/usr/bin/python3

import amulet
import pika
import time
import datetime

d = amulet.Deployment(series='trusty')

d.add('rabbitmq-server')
d.expose('rabbitmq-server')

# Don't forget to expose using d.expose(service)

try:
    # TODO(billy-olsen), juju test --timeout fails to pass the timeout values
    # into the environment and the charm isn't the best of places to select
    # a viable timeout since so muc is attributed to the environment anyways.
    # Need to fix this the right way, but for now we'll bump the timeout.
    d.setup(timeout=2700)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

server = d.sentry.unit['rabbitmq-server/0']
host = server.info['public-address']


# Connects without ssl
print("Running tests with SSL disabled...")
try:
    print("Attempting to connect to {}...".format(host))
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   ssl=False))
    print("Successfully connected.")
except Exception as e:
    amulet.raise_status(
        amulet.FAIL,
        "Insecure connection failed with ssl=off: {}".format(str(e))
    )

# Doesn't connect with ssl
try:
    print("Attempting to connect securely...")
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   ssl=True))
except Exception as e:
    print("Successfully did NOT connect.")
    pass
else:
    amulet.raise_status(
        amulet.FAIL,
        'SSL enabled when it shouldn\'t.'
    )

print("Setting ssl=on...")
d.configure('rabbitmq-server', {
    'ssl': 'on'
})

# Requires rabbit to come back up, let's give it a few seconds
time.sleep(10)

# There's a race for changing the configuration of a deployment.
# The configure from the juju client side happens fairly quickly, and the
# sentry.wait() can fire before the config-changed hooks do, which causes
# the wait to end... 
d.sentry.wait()

# Connects without ssl
try:
    print("Attempting to connect insecurely with ssl=on...")
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   ssl=False))
    print("Successfully connected.")
except Exception as e:
    amulet.raise_status(
        amulet.FAIL,
        "Insecure connection fails with ssl=on: {}".format(str(e))
    )

# Connects with ssl
try:
    print("Attempting to connect securely with ssl=on...")
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   port=5671,
                                                                   ssl=True))
    print("Successfully connected.")
except Exception as e:
    st = str(datetime.datetime.now())
    amulet.raise_status(
        amulet.FAIL,
        "{} Secure connection fails with ssl=on: {}".format(st, str(e))
    )

print("Setting ssl=only...")
d.configure('rabbitmq-server', {
    'ssl': 'only'
})

time.sleep(10)
d.sentry.wait()


# Doesn't connect without ssl
try:
    print("Attmpting to connect insecurely with ssl=only...")
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   ssl=False))
except Exception as e:
    print("Successfully did NOT connect")
    pass
else:
    amulet.raise_status(
        amulet.FAIL,
        "Connects without SSL when it shouldn't"
    )

# Connects with ssl
try:
    connection = pika.BlockingConnection(pika.ConnectionParameters(host=host,
                                                                   ssl=True))
except Exception as e:
    amulet.raise_status(
        amulet.FAIL,
        "Secure connection fails with ssl=only: {}".format(str(e))
    )
